import PavelLayout from "../components/PavelLayout";
import { calcularResumo, carregarSessoes, dominioPrioritario, DOMINIOS_ECO } from "../data/progresso";

const classificar = (valor) => valor >= 80 ? { texto: "Excelente nível de preparação", conquista: "🏆 Conquista superior" } : valor >= 70 ? { texto: "Bom nível de preparação", conquista: "🎉 Conquista alcançada" } : { texto: "Reforce sua preparação", conquista: "" };
export default function Desempenho() {
  const resumo = calcularResumo(carregarSessoes()), foco = dominioPrioritario(resumo), faixa = classificar(resumo.percentual);
  return <PavelLayout titulo="Desempenho" subtitulo="Diagnóstico atual com base nas sessões que você concluiu.">
    <section className="metricGrid"><article className="metricCard"><span>Taxa geral de acerto</span><strong>{resumo.percentual === null ? "--" : `${resumo.percentual}%`}</strong></article><article className="metricCard"><span>Questões respondidas</span><strong>{resumo.questoes}</strong></article><article className="metricCard"><span>Acertos</span><strong>{resumo.acertos}</strong></article><article className="metricCard"><span>Erros</span><strong>{resumo.erros}</strong></article></section>
    {resumo.questoes ? <section className="dashboardGrid"><article className="surface"><h2>Desempenho por Domínio ECO</h2><div className="domainList">{DOMINIOS_ECO.map(({ chave, nome }) => { const valor = resumo.dominios[chave].percentual; return <div className="domainRow" key={chave}><span>{nome}</span><div className="track"><div className="fill" style={{ width: `${valor || 0}%` }} /></div><strong>{valor === null ? "--" : `${valor}%`}</strong></div>; })}</div></article><article className="surface"><h2>Faixas de referência do Pavel PMP Simulator</h2><p className="muted referenceNote">Indicadores pedagógicos internos para orientar sua preparação.</p><div className="detailList"><div><span>Classificação geral</span><strong className="classification">{faixa.texto}</strong></div>{faixa.conquista && <div><span>Conquista</span><strong className="achievement">{faixa.conquista}</strong></div>}<div><span>Domínio para atenção</span><strong className="green">{foco?.nome || "--"}</strong></div><div><span>Desempenho no domínio</span><strong>{foco ? `${foco.percentual}%` : "--"}</strong></div></div></article></section> : <section className="surface emptyState"><div className="emptyIcon">↗</div><h2>Seu diagnóstico começará após a primeira sessão</h2><p>Conclua um simulado ou estudo para visualizar acertos, erros, classificação e desempenho por domínio ECO.</p></section>}
  </PavelLayout>;
}
