import PavelLayout from "../components/PavelLayout";
import { calcularResumo, carregarSessoes, DOMINIOS_ECO, formatarDuracao } from "../data/progresso";

export default function Estatisticas() {
  const sessoes = carregarSessoes(), resumo = calcularResumo(sessoes);
  return <PavelLayout titulo="Estatísticas" subtitulo="Evolução acumulada da sua preparação.">
    <section className="metricGrid"><article className="metricCard"><span>Questões respondidas</span><strong>{resumo.questoes}</strong></article><article className="metricCard"><span>Taxa média de acerto</span><strong>{resumo.percentual === null ? "--" : `${resumo.percentual}%`}</strong></article><article className="metricCard"><span>Sessões realizadas</span><strong>{resumo.sessoes}</strong></article><article className="metricCard"><span>Tempo total de estudo</span><strong>{formatarDuracao(resumo.tempoSegundos)}</strong></article></section>
    {sessoes.length ? <section className="dashboardGrid"><article className="surface chartSurface"><span className="filterStub">Filtros por período · em breve</span><h2>Evolução da taxa de acerto</h2><div className="chartLayout"><span className="chartYAxis">Taxa de acerto (%)</span><div className="chartScale" aria-hidden="true"><span>100%</span><span>50%</span><span>0%</span></div><div className="chart" role="img" aria-label="Taxa de acerto por sessão concluída">{sessoes.map((item, indice) => <div className="chartBar" key={item.id} style={{ height: `${Math.max(3, item.percentual)}%` }} title={`Sessão ${indice + 1}, ${new Date(item.data).toLocaleDateString("pt-BR")}: ${item.percentual}%`}><strong>{item.percentual}%</strong><span>{new Date(item.data).toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" })}</span></div>)}</div></div><p className="chartXAxis">Sessões concluídas (data)</p></article><article className="surface"><h2>Domínios ECO — taxa de acerto (%)</h2><div className="domainList">{DOMINIOS_ECO.map(({ chave, nome }) => { const valor = resumo.dominios[chave].percentual; return <div className="domainRow" key={chave}><span>{nome}</span><div className="track" title={`${nome}: ${valor === null ? "sem dados" : `${valor}%`}`}><div className="fill" style={{ width: `${valor || 0}%` }} /></div><strong>{valor === null ? "--" : `${valor}%`}</strong></div>; })}</div></article></section> : <section className="surface emptyState"><div className="emptyIcon">▥</div><h2>A evolução aparecerá aqui</h2><p>Ainda não há dados acumulados. Seus gráficos serão construídos somente com resultados reais de sessões concluídas.</p></section>}
  </PavelLayout>;
}
